#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rspec-its
Version  : 1.2.0
Release  : 4
URL      : https://rubygems.org/downloads/rspec-its-1.2.0.gem
Source0  : https://rubygems.org/downloads/rspec-its-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-cucumber
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations

%description
# RSpec::Its [![Build Status](https://travis-ci.org/rspec/rspec-its.svg)](https://travis-ci.org/rspec/rspec-its)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rspec-its-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-rspec-its.gemspec

%build
gem build rubygem-rspec-its.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rspec-its-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rspec-its-1.2.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/Changelog.md
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/cucumber.yml
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/features/its.feature
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/features/step_definitions/additional_cli_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/lib/rspec/its.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/lib/rspec/its/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/rspec-its.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/script/test_all
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/spec/rspec/its_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-its-1.2.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/rspec-its-1.2.0.gemspec
